### ISSUE TITLE
User Story 2.3 - Contractor Availability

### ISSUE THREAD

**Issue by temidosu** [temidosu/DB-GUI-Thurs-Group-1#2]
User should be able to see when a contractor is available or busy so that the user can know which contractors have space. 

Given a client is logged in, when viewing a worker/contractor that is not accepting requests, then the worker/contractor profile should have a "not accepting requests".

Given a client is not logged in, when viewing a worker/contractor that is not accepting requests, then the user will be prompted with a "sign up/log in button.

**Comment by SimonAsenime** [comment]
Dropped.
