### ISSUE TITLE
User Story 7.4 As a client I want to be notified when a tradesmen has accepted or declined a job So that I stay updated in my search for someone to do the job

### ISSUE THREAD

**Issue by ostenloo** [temidosu/DB-GUI-Thurs-Group-1#29]
Given that I have submitted a job request,  when the tradesman accepts my request, then I should receive an immediate update from the website (email/inbox notification) notifying me that the job has been accepted

Given that I have submitted a job request,  when the tradesman accepts my request, then I should receive an immediate update from the website (email/inbox notification) notifying me that the job has been accepted

**Comment by SimonAsenime** [comment]
Dropped.
