### ISSUE TITLE
User Story 2.4 and 2.5 - Notification when request has been accepted/denied

### ISSUE THREAD

**Issue by temidosu** [temidosu/DB-GUI-Thurs-Group-1#3]
Clients should be notified in their inbox when a contractor accepts or denies a request from them.

Story 2.4
Given a worker/contractor accepts a request, when the client is on the software, the client should receive a notification alerting them of the accepted request and the worker/contractors contact information.

Given a worker/contractor accepts a request, when the client is no on the software, the client should be able to see a notification icon on their inbox with the respective worker/contractors contact information on their request item.

Story 2.5
Given a worker/contractor denies a request, when the client is on the software, the client should receive a notification alerting them of their denied request and lead them back to  workers/contractors in their area

Given a worker/contractor denies a request, when the client is on the software, the client should be able to see a notifiation icon on their inbox with a "denied" message on their request item.

**Comment by SimonAsenime** [comment]
Dropped.
