### ISSUE TITLE
User Story 8.1 As a company I want to view if workers are available for full-time or contract work so that I know who to hire for potential projects

### ISSUE THREAD

**Issue by ostenloo** [temidosu/DB-GUI-Thurs-Group-1#31]
Given a company is looking to hire a worker for a job, when they are reviewin the worker's profile, then they can see if they are available for full time jobs or just singular hires.

Given a company looking to hire full time workers, when the worker makes it clear they are a full-time worker, then the company can target this worker and reach out

**Comment by SimonAsenime** [comment]
Dropped.
