### ISSUE TITLE
User Story 5.3 - View Reviews

### ISSUE THREAD

**Issue by SimonAsenime** [temidosu/DB-GUI-Thurs-Group-1#32]
### The user story details it as such: As a homeowner, I want to view reviews from previous clients of a worker, so that I can be more informed about their work.

- Given a feed/post, when I view a recommendation post, then I can view reviews from other users of the platform about the worker or their work.
- Given a profile page, when the profile page is clicked, then a small list of popular positive recommendations about a worker is highlighted in a subsection of the page.

**Comment by ostenloo** [comment]
reviews are shown but no ordering them yet
