### ISSUE TITLE
User Story 5.4 - View Closest Workers

### ISSUE THREAD

**Issue by SimonAsenime** [temidosu/DB-GUI-Thurs-Group-1#37]
### The user story details it as such: As a homeowner, I want to view the nearest located workers, so that I can find a worker who can reach my desired location in time.

- Given a search bar/page, when I search for a worker, then I can view a populated page of workers that match my criteria with a tag informing me what city, state they're located in.
- Given a search result, when the result is viewed, the worker profile that is the same city client should render at the top of the page for better visibility.

**Comment by ostenloo** [comment]
I do this by matching ZipCode-- can change it so that it matches the first 3 digits so that it's by area
