### ISSUE TITLE
User Story 5.5 - Search by Name

### ISSUE THREAD

**Issue by SimonAsenime** [temidosu/DB-GUI-Thurs-Group-1#38]
### The user story details it as such: As a homeowner, I want to search by name, so that I can find a worker I was recommended by a colleague.

- Given a search bar/page, when I enter a name (first or last), then I can get a populated page of workers that match the given name.
- Given a search bar/page, when I enter a name (first or last), then I get notified if no worker that matches the criteria exists.

**Comment by ostenloo** [comment]
still have to say "no worker matches the criteria", also maybe search needs work?
