### ISSUE TITLE
User Story 2.2 - Check the Status of a Request

### ISSUE THREAD

**Issue by jdmayssmu** [temidosu/DB-GUI-Thurs-Group-1#9]
Given a client is logged in, when looking for the request's status, then they should be able to access all submitted requests via an inbox with the current status on each request item.

Given a client is not logged in, when they want to request a worker/contractor, then the user will be prompted with a "sign up/log in" button when viewing worker/contractor profiles.

**Comment by ostenloo** [comment]
maybe add filtering to myProjects page
